FROM node:20-alpine AS base

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/
COPY packages/contracts/package*.json ./packages/contracts/
COPY packages/foundations/package*.json ./packages/foundations/

FROM base AS development

WORKDIR /app

RUN npm ci

COPY . .

EXPOSE 3000

WORKDIR /app/apps/api

CMD ["npm", "run", "start:dev"]
